---
apiVersion: v1
kind: Service
metadata:
 name: k-rail
 namespace: {{ .Release.Namespace }}
 labels:
    name: k-rail
spec:
  ports:
  - name: validatingwebhook
    port: 443
    targetPort: 10250
  selector:
    name: k-rail
